name: 🛠️ .NET Build on Pull Request

on:
  pull_request:
    branches:
      - main
      - master  # Lägg till andra brancher om nödvändigt

jobs:
  build:
    name: 🔧 Build .NET Project
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout koden
        uses: actions/checkout@v4

      - name: 🟣 Installera .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Ändra vid behov

      - name: 🛠️ Bygg projektet
        run: dotnet build --configuration Release
