name: 🛠️ .NET Build on Pull Request

on:
  pull_request:
    branches:
      - main
      - master  # Lägg till andra brancher om nödvändigt

jobs:
  build:
    name: 🔧 Build .NET Project
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout koden
        uses: actions/checkout@v4

      - name: 🟣 Installera .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Ändra vid behov

      - name: 🛠️ Bygg projektet
        run: dotnet build --configuration Release

  notify:    
    runs-on: ubuntu-latest
    needs: build
    if: always() # ensures notify runs even if build fails
    steps: 
        - name: Send Discord Notification 
          run: |
           STATUS=${{ needs.build.result }}
           curl -H "Content-Type: application/json" \
                -X POST \
                -d "{\"content\": \" :bell: PR Build finished with status: **$STATUS**\"}" \
            ${{ https://discord.com/api/webhooks/1414125419610771466/Xkb9ADuwivDV3vwW0fl-pjpA_bSoq7GRFHfhTucFBAsoAx7TFNW7XPGArLLQESICpfvL Här är hook till alla att kopiera}}
